name: flutter_app
description: My journey to learn flutter.

dependencies:
  flutter:
    sdk: flutter
  sqflite: 
  path_provider: 
  intl: ^0.15.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

  - assets/images/ 

  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf
   
